# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connection.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63onnection.proto\x12\x19\x62\x61\x62\x61ra_project.connection\"\x1a\n\x07\x43onnect\x12\x0f\n\x07version\x18\x01 \x01(\t\"\x1b\n\x08Received\x12\x0f\n\x07version\x18\x01 \x01(\t\"\xb9\x01\n\x06Packet\x12\x0f\n\x07version\x18\x01 \x01(\t\x12:\n\x04type\x18\x02 \x01(\x0e\x32,.babara_project.connection.Packet.PacketType\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"T\n\nPacketType\x12\r\n\tUNDEFINED\x10\x00\x12\x0b\n\x07\x43ONNECT\x10\x01\x12\x0c\n\x08RECEIVED\x10\x02\x12\r\n\tBOAT_DATA\x10\x03\x12\r\n\tPATH_DATA\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONNECT']._serialized_start=47
  _globals['_CONNECT']._serialized_end=73
  _globals['_RECEIVED']._serialized_start=75
  _globals['_RECEIVED']._serialized_end=102
  _globals['_PACKET']._serialized_start=105
  _globals['_PACKET']._serialized_end=290
  _globals['_PACKET_PACKETTYPE']._serialized_start=206
  _globals['_PACKET_PACKETTYPE']._serialized_end=290
# @@protoc_insertion_point(module_scope)
