# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
# Protobuf Python Version: 5.26.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import latlng_pb2 as latlng__pb2
from . import timestamp_pb2 as timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x13\x62\x61\x62\x61ra_project.data\x1a\x0clatlng.proto\x1a\x0ftimestamp.proto\"\xc8\x02\n\x08\x42oatData\x12\x0f\n\x07version\x18\x01 \x01(\t\x12?\n\x08\x66\x65\x61tures\x18\x02 \x03(\x0b\x32-.babara_project.data.BoatData.BoatDataFeature\x1a\xba\x01\n\x0f\x42oatDataFeature\x12\x13\n\x0btemperature\x18\x01 \x01(\x01\x12\r\n\x05\x64\x65pth\x18\x02 \x01(\x01\x12\x32\n\x05layer\x18\x03 \x01(\x0e\x32#.babara_project.data.BoatData.Layer\x12(\n\x04time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12%\n\x08geometry\x18\x05 \x01(\x0b\x32\x13.google.type.LatLng\"-\n\x05Layer\x12\x0b\n\x07SURFACE\x10\x00\x12\n\n\x06MIDDLE\x10\x01\x12\x0b\n\x07SEA_BED\x10\x02\"@\n\x08PathData\x12\x0f\n\x07version\x18\x01 \x01(\t\x12#\n\x06points\x18\x03 \x03(\x0b\x32\x13.google.type.LatLngb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOATDATA']._serialized_start=67
  _globals['_BOATDATA']._serialized_end=395
  _globals['_BOATDATA_BOATDATAFEATURE']._serialized_start=162
  _globals['_BOATDATA_BOATDATAFEATURE']._serialized_end=348
  _globals['_BOATDATA_LAYER']._serialized_start=350
  _globals['_BOATDATA_LAYER']._serialized_end=395
  _globals['_PATHDATA']._serialized_start=397
  _globals['_PATHDATA']._serialized_end=461
# @@protoc_insertion_point(module_scope)
